# Generated by Django 4.2.1 on 2023-05-29 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2023, 5, 29, 21, 14, 48, 820704))),
            ],
        ),
    ]
